import { activityPriorities, activityStatuses, type ActivityType } from "@/types/activity";
import type { ActivityTemplateFragment, ContextOverlay, ServiceOverlay, TemplateField } from "@/lib/activity-templates/types";

const field = (id: string, section: string, label: string, key: string, kind: TemplateField["kind"] = "text", source: TemplateField["source"] = "details", extra: Partial<TemplateField> = {}): TemplateField => ({ id, section, label, key, kind, source, ...extra });
const fields = (section: string, entries: Array<[string, string, TemplateField["kind"]?]>) => entries.map(([key, label, kind]) => field(`field:${key}`, section, label, key, kind));

export const baseTemplate: ActivityTemplateFragment = { id: "base", label: "Activity-Basis", fields: [
  field("base:title", "Basisdaten", "Titel", "title", "text", "activity"),
  field("base:status", "Basisdaten", "Status", "status", "select", "activity", { options: activityStatuses }),
  field("base:priority", "Basisdaten", "Priorität", "priority", "select", "activity", { options: activityPriorities }),
  field("base:responsible", "Basisdaten", "Verantwortlicher", "responsibleId", "text", "activity", { placeholder: "Name oder Kennung" }),
  field("base:due", "Basisdaten", "Fälligkeit / Termin", "plannedAt", "datetime", "activity"),
  field("base:description", "Basisdaten", "Beschreibung", "description", "textarea", "activity"),
] };

const conversation = fields("Gespräch", [["contactPerson", "Ansprechpartner"], ["topic", "Thema", "textarea"], ["result", "Ergebnis", "textarea"], ["followUp", "Rückruf / Wiedervorlage", "date"]]);
const templates: Record<ActivityType, ActivityTemplateFragment> = {
  Angebotsaufnahme: { id: "type:Angebotsaufnahme", label: "Baustellenbesuch", fields: fields("Baustelle", [["siteAddress", "Baustellenadresse"], ["siteDescription", "Baustellenbeschreibung", "textarea"], ["siteNotes", "Hinweise", "textarea"], ["callbackRequired", "Rückruf erforderlich", "checkbox"]]), checklist: [{ id: "site-access", label: "Baustellenzugang geklärt", requirement: "required" }, { id: "photos", label: "Fotos aufgenommen", requirement: "conditional" }], documents: [{ id: "photos", label: "Baustellenfotos", documentType: "Foto", requirement: "conditional" }], context: [{ id: "site", label: "Baustelle", detailKey: "siteAddress" }, { id: "callback", label: "Rückruf", detailKey: "callbackRequired" }] },
  Angebot: { id: "type:Angebot", label: "Angebot", fields: fields("Angebot", [["scope", "Leistungsumfang", "textarea"], ["validUntil", "Gültig bis", "date"], ["openCalculation", "Offene Kalkulationspunkte", "textarea"]]), followUps: [{ id: "offer-follow-up", label: "Angebot nachfassen", targetType: "Telefonat", trigger: { status: "abgeschlossen" } }], context: [{ id: "valid", label: "Gültig bis", detailKey: "validUntil" }] },
  Montage: { id: "type:Montage", label: "Montage", fields: fields("Montagevorbereitung", [["plannedWork", "Geplante Arbeiten", "textarea"], ["siteAccess", "Baustellenzugang"], ["materialStatus", "Materialstatus"], ["crewPreparation", "Kolonne"], ["riskAssessment", "Gefährdungsbeurteilung"], ["openRequirements", "Offene Voraussetzungen", "textarea"]]), checklist: [{ id: "site-access", label: "Baustelle zugänglich", requirement: "required", blocker: true }, { id: "material-ready", label: "Material vorhanden", requirement: "required" }, { id: "crew-ready", label: "Kolonne bestätigt", requirement: "required" }, { id: "assembly-instruction", label: "Montageanweisung vorhanden", requirement: "required" }, { id: "risk-assessment", label: "Gefährdungsbeurteilung vorhanden", requirement: "required" }], documents: [{ id: "assembly-plan", label: "Montageplan", documentType: "Plan", requirement: "required" }], followUps: [{ id: "control-after-assembly", label: "Kontrolle vorbereiten", targetType: "Kontrolle", trigger: { status: "abgeschlossen" } }], context: [{ id: "material", label: "Materialstatus", detailKey: "materialStatus" }, { id: "crew", label: "Kolonne", detailKey: "crewPreparation" }, { id: "weather", label: "Wetter", value: "Noch nicht angebunden" }], blockerRules: [{ id: "material-missing", label: "Materialstatus fehlt oder meldet fehlendes Material", kind: "negative-detail", detailKey: "materialStatus", negativeValues: ["", "fehlt", "nicht vorhanden", "offen"] }, { id: "crew-missing", label: "Kolonne fehlt", kind: "missing-detail", detailKey: "crewPreparation" }] },
  Umbau: { id: "type:Umbau", label: "Umbau", fields: fields("Umbauvorbereitung", [["conversionScope", "Geplanter Umbau", "textarea"], ["existingCondition", "Vorhandener Zustand", "textarea"], ["restrictedAreas", "Sperrbereiche"], ["materialStatus", "Materialstatus"], ["openRequirements", "Offene Voraussetzungen", "textarea"]]), checklist: [{ id: "change-plan", label: "Änderungsumfang geklärt", requirement: "required" }, { id: "material-ready", label: "Material vorhanden", requirement: "required", blocker: true }], followUps: [{ id: "control-after-conversion", label: "Kontrolle vorbereiten", targetType: "Kontrolle", trigger: { status: "abgeschlossen" } }], context: [{ id: "material", label: "Materialstatus", detailKey: "materialStatus" }] },
  Abbau: { id: "type:Abbau", label: "Demontage", fields: fields("Demontagevorbereitung", [["dismantlingScope", "Geplanter Abbau", "textarea"], ["siteAccess", "Baustellenzugang"], ["returnTransport", "Materialabtransport"], ["openRequirements", "Offene Voraussetzungen", "textarea"]]), checklist: [{ id: "deregistration", label: "Baustelle freigemeldet", requirement: "required" }, { id: "return-transport", label: "Rücktransport geklärt", requirement: "required" }], followUps: [{ id: "final-measurement", label: "Schlussaufmaß vorbereiten", targetType: "Aufmaß", trigger: { status: "abgeschlossen" } }], context: [{ id: "transport", label: "Abtransport", detailKey: "returnTransport" }] },
  Kontrolle: { id: "type:Kontrolle", label: "Kontrolle", fields: fields("Kontrolle", [["checkpoints", "Prüfpunkte", "textarea"], ["defects", "Mängel", "textarea"], ["actionRequired", "Restarbeiten / Handlungsbedarf", "textarea"]]), checklist: [{ id: "anchoring", label: "Verankerung geprüft", requirement: "required" }, { id: "side-protection", label: "Seitenschutz geprüft", requirement: "required" }, { id: "decks", label: "Beläge geprüft", requirement: "required" }, { id: "access", label: "Zugänge geprüft", requirement: "required" }, { id: "photos", label: "Kontrollfotos vorhanden", requirement: "required" }], documents: [{ id: "control-photos", label: "Kontrollfotos", documentType: "Foto", requirement: "required" }], followUps: [{ id: "repair-defect", label: "Nacharbeit vorbereiten", targetType: "Montage", trigger: { detailKey: "defects" } }, { id: "progress-invoice", label: "Abschlagsrechnung vorbereiten", targetType: "Rechnung", trigger: { status: "abgeschlossen" } }], context: [{ id: "defects", label: "Mängel", detailKey: "defects" }, { id: "remaining", label: "Restarbeiten", detailKey: "actionRequired" }] },
  Aufmaß: { id: "type:Aufmaß", label: "Aufmaß", fields: fields("Aufmaß", [["measurements", "Maße", "textarea"], ["quantities", "Mengen", "textarea"], ["sketches", "Skizzen / Hinweise", "textarea"], ["notes", "Notizen", "textarea"]]), checklist: [{ id: "building-section", label: "Gebäudeseite / Abschnitt erfasst", requirement: "required" }, { id: "dimensions", label: "Länge, Höhe und Fläche erfasst", requirement: "required" }, { id: "photos", label: "Fotos vorhanden", requirement: "required" }, { id: "open-questions", label: "Offene Fragen geklärt", requirement: "conditional" }], documents: [{ id: "measurement", label: "Aufmaß", documentType: "Aufmaß", requirement: "required" }, { id: "measurement-photos", label: "Fotos", documentType: "Foto", requirement: "required" }], context: [{ id: "quantity", label: "Mengen", detailKey: "quantities" }] },
  Nachtrag: { id: "type:Nachtrag", label: "Nachtrag", fields: fields("Nachtrag", [["reason", "Anlass"], ["additionalScope", "Zusätzliche Leistung", "textarea"], ["customerApproval", "Kundenfreigabe"], ["openPoints", "Offene Punkte", "textarea"]]), documents: [{ id: "signature", label: "Kundenfreigabe / Unterschrift", documentType: "Unterschrift", requirement: "conditional" }], context: [{ id: "approval", label: "Freigabe", detailKey: "customerApproval" }] },
  Materiallieferung: { id: "type:Materiallieferung", label: "Materiallieferung", fields: fields("Material", [["materialStatus", "Material / Lieferumfang", "textarea"], ["deliveryAddress", "Abladestelle"], ["timeWindow", "Zeitfenster"], ["openRequirements", "Offene Voraussetzungen", "textarea"]]), checklist: [{ id: "material-loaded", label: "Material verladen", requirement: "required" }, { id: "delivery-access", label: "Zufahrt geklärt", requirement: "required" }], context: [{ id: "material", label: "Materialstatus", detailKey: "materialStatus" }, { id: "time", label: "Zeitfenster", detailKey: "timeWindow" }] },
  Materialabholung: { id: "type:Materialabholung", label: "Materialabholung", fields: fields("Material", [["materialStatus", "Abzuholendes Material", "textarea"], ["pickupPoint", "Abholstelle"], ["loadingConditions", "Ladebedingungen"], ["openRequirements", "Offene Voraussetzungen", "textarea"]]), checklist: [{ id: "pickup-ready", label: "Material abholbereit", requirement: "required" }, { id: "loading-access", label: "Ladezugang geklärt", requirement: "required" }], context: [{ id: "material", label: "Materialstatus", detailKey: "materialStatus" }] },
  Reklamation: { id: "type:Reklamation", label: "Reklamation", fields: fields("Reklamation", [["contactPerson", "Ansprechpartner"], ["complaint", "Beanstandung", "textarea"], ["actionRequired", "Handlungsbedarf", "textarea"], ["responseDue", "Rückmeldung bis", "date"]]), documents: [{ id: "complaint-photos", label: "Fotos zur Reklamation", documentType: "Foto", requirement: "conditional" }], followUps: [{ id: "complaint-control", label: "Kontrolle vorbereiten", targetType: "Kontrolle", trigger: { detailKey: "actionRequired" } }], context: [{ id: "contact", label: "Ansprechpartner", detailKey: "contactPerson" }, { id: "due", label: "Rückmeldung", detailKey: "responseDue" }] },
  Besprechung: { id: "type:Besprechung", label: "Besprechung", fields: conversation, context: [{ id: "contact", label: "Ansprechpartner", detailKey: "contactPerson" }, { id: "follow", label: "Termin", detailKey: "followUp" }] },
  Telefonat: { id: "type:Telefonat", label: "Telefonat", fields: conversation, followUps: [{ id: "callback", label: "Rückruf vorbereiten", targetType: "Telefonat", trigger: { detailKey: "followUp" } }], context: [{ id: "callback", label: "Rückruf", detailKey: "followUp" }, { id: "contact", label: "Ansprechpartner", detailKey: "contactPerson" }] },
  Sonstiges: { id: "type:Sonstiges", label: "Sonstiges", fields: fields("Arbeitsauftrag", [["context", "Anlass", "textarea"], ["expectedResult", "Erwartetes Ergebnis", "textarea"], ["openPoints", "Offene Punkte", "textarea"]]), context: [{ id: "result", label: "Erwartetes Ergebnis", detailKey: "expectedResult" }] },
};

export const serviceOverlayRegistry: Record<ServiceOverlay, ActivityTemplateFragment> = {
  "Fassadengerüst": { id: "service:facade", label: "Fassadengerüst", fields: fields("Fassadengerüst", [["facadeSide", "Gebäudeseite"], ["facadeArea", "Gerüstfläche"], ["scaffoldClass", "Last- / Breitenklasse"]]), checklist: ["Unterlagsholz", "Fußplatten / Spindeln", "Rahmen", "Beläge", "Geländer", "Bordbretter", "Diagonalen", "Anker", "Durchstiege"].map((label) => ({ id: `facade:${label.toLocaleLowerCase("de-DE").replaceAll(" ", "-")}`, label: `${label} vorhanden`, requirement: "required" as const })) },
  "Dachfangschutz": { id: "service:roof-guard", label: "Dachfangschutz", fields: fields("Dachfangschutz", [["roofGuardSide", "Gebäudeseite"], ["roofGuardNeededAt", "Benötigt am", "date"]]), checklist: [{ id: "roof:side-protection", label: "Bordbretter / Seitenschutz vorhanden", requirement: "required" }, { id: "roof:brackets", label: "Konsolen vorhanden", requirement: "required" }, { id: "roof:special-parts", label: "Sonderteile geklärt", requirement: "conditional" }] },
  "Treppenturm": { id: "service:stair-tower", label: "Treppenturm", fields: fields("Treppenturm", [["stairTowerLocation", "Standort"], ["stairTowerHeight", "Höhe"]]), checklist: [{ id: "stairs:foundation", label: "Gründung geprüft", requirement: "required" }, { id: "stairs:connection", label: "Anschluss geklärt", requirement: "required" }] },
  "Schutzgerüst": { id: "service:protection", label: "Schutzgerüst", fields: fields("Schutzgerüst", [["protectionType", "Schutzart"], ["hazardArea", "Gefahrenbereich"]]), checklist: [{ id: "protection:barrier", label: "Gefahrenbereich abgesperrt", requirement: "required" }] },
  "Industriegerüst": { id: "service:industry", label: "Industriegerüst", fields: fields("Industriegerüst", [["plantArea", "Anlagenbereich"], ["plantRelease", "Anlagenfreigabe"]]), checklist: [{ id: "industry:release", label: "Anlagenfreigabe vorhanden", requirement: "required", blocker: true }] },
  "Hängegerüst": { id: "service:suspended", label: "Hängegerüst", fields: fields("Hängegerüst", [["suspension", "Aufhängung"], ["rescueConcept", "Rettungskonzept"]]), checklist: [{ id: "suspended:anchors", label: "Aufhängepunkte geprüft", requirement: "required", blocker: true }, { id: "suspended:rescue", label: "Rettungskonzept vorhanden", requirement: "required", blocker: true }] },
  "Wetterschutzdach": { id: "service:weather-roof", label: "Wetterschutzdach", fields: fields("Wetterschutzdach", [["roofSpan", "Spannweite"], ["drainage", "Entwässerung"]]), checklist: [{ id: "weather:wind", label: "Windgrenzen festgelegt", requirement: "required" }, { id: "weather:drainage", label: "Entwässerung geklärt", requirement: "required" }] },
  "Sonderkonstruktion": { id: "service:special", label: "Sonderkonstruktion", fields: fields("Sonderkonstruktion", [["specialConstruction", "Konstruktionsbeschreibung", "textarea"]]), checklist: [{ id: "special:plan", label: "Planung vorhanden", requirement: "required" }], documents: [{ id: "special-plan", label: "Plan", documentType: "Plan", requirement: "required", blocker: true }] },
};

export const contextOverlayRegistry: Record<ContextOverlay, ActivityTemplateFragment> = {
  "öffentlicher Raum": { id: "context:public", label: "Öffentlicher Raum", fields: fields("Öffentlicher Raum", [["specialUseStatus", "Sondernutzungsstatus"]]), checklist: [{ id: "public:special-use", label: "Sondernutzung vorhanden", requirement: "required" }], documents: [{ id: "special-use", label: "Sondernutzung", documentType: "Sondernutzung", requirement: "required", blocker: true }], blockerRules: [{ id: "special-use-missing", label: "Sondernutzung fehlt", kind: "missing-document", documentType: "Sondernutzung" }] },
  "Privatgrundstück": { id: "context:private", label: "Privatgrundstück", context: [{ id: "private-site", label: "Grundstück", value: "Privatgrundstück" }] },
  "Kran erforderlich": { id: "context:crane", label: "Kran erforderlich", fields: fields("Kran", [["cranePlanning", "Kranplanung"], ["craneDate", "Kraneinsatz", "date"]]), checklist: [{ id: "crane:planned", label: "Kran eingeplant", requirement: "required", blocker: true }] },
  "Statik erforderlich": { id: "context:structural", label: "Statik erforderlich", checklist: [{ id: "structural:available", label: "Statik vorhanden", requirement: "required" }], documents: [{ id: "structural", label: "Statik", documentType: "Statik", requirement: "required", blocker: true }], blockerRules: [{ id: "structural-missing", label: "Erforderliche Statik fehlt", kind: "missing-document", documentType: "Statik" }] },
  "Nachtarbeit": { id: "context:night", label: "Nachtarbeit", fields: fields("Arbeitszeit", [["nightWorkWindow", "Nachtarbeitszeitfenster"]]), checklist: [{ id: "night:lighting", label: "Beleuchtung geklärt", requirement: "required" }] },
  "Wochenendarbeit": { id: "context:weekend", label: "Wochenendarbeit", fields: fields("Arbeitszeit", [["weekendWindow", "Wochenendzeitfenster"]]), checklist: [{ id: "weekend:access", label: "Wochenendzugang geklärt", requirement: "required" }] },
};

export const templateRegistry = { base: baseTemplate, types: templates, services: serviceOverlayRegistry, contexts: contextOverlayRegistry } as const;
export function getTypeTemplate(type: ActivityType) { return templates[type]; }
