"use client";

import Image from "next/image";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { inferContextOverlays, isTemplateTransitionAllowed, resolveActivityTemplate, type ResolvedActivityTemplate, type TemplateField } from "@/lib/activity-templates";
import { readActivities, readProjectCore, readProjects, writeActivities } from "@/lib/local-storage";
import type { Activity, ActivityAttachment, ActivityComment, ActivityDetailValue, ActivityHistoryEntry, ActivityOpenItem } from "@/types/activity";
import type { ProjectDocument } from "@/types/document";
import type { ProjectNote } from "@/types/note";
import type { ProjectPhoto } from "@/types/photo";
import type { Project } from "@/types/project";
import type { SiteVisit } from "@/types/site-visit";

const tabs = ["Übersicht", "Checkliste", "Fotos", "Dokumente", "Kommentare", "Verlauf"] as const;
type Tab = (typeof tabs)[number];
type WorkspaceData = { project: Project; activity: Activity; visits: SiteVisit[]; photos: ProjectPhoto[]; documents: ProjectDocument[]; notes: ProjectNote[] };
type ChangeKind = ActivityHistoryEntry["kind"];

export default function ActivityPage() {
  const { projectId, activityId } = useParams<{ projectId: string; activityId: string }>();
  const [data, setData] = useState<WorkspaceData | null>();
  const [activeTab, setActiveTab] = useState<Tab>("Übersicht");

  useEffect(() => { const timer = window.setTimeout(() => { const store = readProjectCore(); const project = readProjects().find((item) => item.id === projectId); const activity = store.activities.find((item) => item.id === activityId); if (!project || !activity || activity.projectId !== projectId) { setData(null); return; } const visits = store.visits.filter((item) => item.activityId === activityId); const visitIds = new Set(visits.map((item) => item.id)); setData({ project, activity, visits, photos: store.photos.filter((item) => item.projectId === projectId && visitIds.has(item.visitId)), documents: store.documents.filter((item) => item.projectId === projectId), notes: store.notes.filter((item) => item.projectId === projectId && visitIds.has(item.visitId)) }); }, 0); return () => window.clearTimeout(timer); }, [projectId, activityId]);

  function persist(next: Activity, kind: ChangeKind, text: string, extraHistory: ActivityHistoryEntry[] = []) { const now = new Date().toISOString(); const history = [...(next.history || initialHistory(next)), historyEntry(kind, text, now), ...extraHistory]; const saved = { ...next, updatedAt: now, history }; writeActivities(readActivities().map((item) => item.id === saved.id ? saved : item)); setData((current) => current ? { ...current, activity: saved } : current); }

  if (data === undefined) return <State text="Activity wird geladen …" />;
  if (data === null) return <State text="Activity nicht gefunden." />;
  const address = formatAddress(data.project);
  const template = resolveActivityTemplate({ type: data.activity.type, services: data.project.services, contexts: inferContextOverlays(data.activity.details), activity: data.activity, documents: data.documents });
  return <AppShell><div className="min-h-full bg-[#070b14] text-white"><div className="sticky top-0 z-40 border-b border-white/[0.08] bg-[#080d17]/95 backdrop-blur-xl"><div className="mx-auto max-w-[1480px] px-5 pt-4 sm:px-8 lg:px-10"><Link href={`/projects/${projectId}`} className="text-xs text-slate-500 hover:text-cyan-300">← {data.project.name}</Link><header className="py-5"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge tone="cyan">{data.activity.type}</Badge><Badge tone="green">{data.activity.status}</Badge><Badge tone={data.activity.priority === "kritisch" ? "rose" : "muted"}>{data.activity.priority}</Badge></div><h1 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">{data.activity.title}</h1></div><dl className="grid grid-cols-2 gap-x-8 gap-y-4 sm:grid-cols-4 lg:min-w-[600px]"><Fact label="Projekt" value={data.project.name} /><Fact label="Baustelle" value={address} /><Fact label="Verantwortlicher" value={data.activity.responsibleId || undefined} /><Fact label="Fälligkeit" value={data.activity.plannedAt ? formatDate(data.activity.plannedAt) : undefined} /></dl></div></header><nav aria-label="Activity-Bereiche" className="scrollbar-hidden flex gap-1 overflow-x-auto border-t border-white/[0.07] py-2">{tabs.map((tab) => <button key={tab} type="button" onClick={() => setActiveTab(tab)} aria-current={activeTab === tab ? "page" : undefined} className={`shrink-0 rounded-lg px-4 py-2.5 text-xs font-medium ${activeTab === tab ? "bg-white text-slate-950" : "text-slate-500 hover:bg-white/[0.05] hover:text-white"}`}>{tab}</button>)}</nav></div></div><div className="mx-auto max-w-[1480px] px-5 sm:px-8 lg:px-10"><div className="grid items-start gap-8 xl:grid-cols-[minmax(0,1fr)_248px]"><main className="min-w-0 py-8"><Content tab={activeTab} data={data} template={template} persist={persist} /></main><Context tab={activeTab} data={data} template={template} /></div></div></div></AppShell>;
}

function Content({ tab, data, template, persist }: { tab: Tab; data: WorkspaceData; template: ResolvedActivityTemplate; persist: (next: Activity, kind: ChangeKind, text: string, extra?: ActivityHistoryEntry[]) => void }) { if (tab === "Übersicht") return <Editor key={data.activity.updatedAt} data={data} template={template} persist={persist} />; if (tab === "Checkliste") return <Checklist activity={data.activity} template={template} persist={persist} />; if (tab === "Fotos") return <Photos data={data} />; if (tab === "Dokumente") return <Documents data={data} template={template} />; if (tab === "Kommentare") return <Comments activity={data.activity} notes={data.notes} persist={persist} />; return <History activity={data.activity} template={template} />; }
function Title({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <header className="mb-8"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-cyan-300">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{text}</p></header>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl bg-white/[0.035] p-5 sm:p-6"><h3 className="font-semibold text-slate-100">{title}</h3><div className="mt-5">{children}</div></section>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="flex min-h-36 items-center justify-center rounded-2xl border border-dashed border-white/10 px-6 text-center text-sm leading-6 text-slate-600">{children}</div>; }

function Editor({ data, template, persist }: { data: WorkspaceData; template: ResolvedActivityTemplate; persist: (next: Activity, kind: ChangeKind, text: string, extra?: ActivityHistoryEntry[]) => void }) { const [draft, setDraft] = useState(data.activity); const [saved, setSaved] = useState(false); const [error, setError] = useState(""); function update(field: TemplateField, value: ActivityDetailValue | string) { setDraft((current) => field.source === "details" ? { ...current, details: { ...current.details, [field.key]: value as ActivityDetailValue } } : ({ ...current, [field.key]: activityFieldValue(field, value) } as Activity)); setSaved(false); setError(""); } function submit(event: FormEvent) { event.preventDefault(); const oldStatus = data.activity.status; const now = new Date().toISOString(); let next = { ...draft, title: draft.title.trim(), description: draft.description.trim(), responsibleId: draft.responsibleId?.trim() || null }; const resolved = resolveActivityTemplate({ type: next.type, services: data.project.services, contexts: inferContextOverlays(next.details), activity: next, documents: data.documents }); if (!isTemplateTransitionAllowed(next.status, resolved.blockers.length)) { setError("Freigabe oder Abschluss ist blockiert. Die offenen Blocker müssen zuerst geklärt werden."); return; } const extra: ActivityHistoryEntry[] = []; if (oldStatus !== next.status) { extra.push(historyEntry("status", `Status von ${oldStatus} auf ${next.status} geändert`, now)); if (next.status === "begonnen" && !next.startedAt) next = { ...next, startedAt: now }; if (next.status === "abgeschlossen") { next = { ...next, endedAt: next.endedAt || now }; extra.push(historyEntry("abgeschlossen", "Activity abgeschlossen", now)); } } persist(next, "bearbeitet", "Activity bearbeitet", extra); setSaved(true); }
  return <form onSubmit={submit}><Title eyebrow={`Template · ${template.label}`} title="Activity bearbeiten" text={`Aufgelöst aus ${template.fragments.map((item) => item.label).join(" + ")}.`} /><div className="space-y-5">{template.sections.map((section) => <Panel key={section.id} title={section.title}><div className="grid gap-5 sm:grid-cols-2">{section.fields.map((field) => <DynamicField key={field.id} field={field} value={templateFieldValue(draft, field)} onChange={(value) => update(field, value)} />)}</div></Panel>)}<OpenItems activity={data.activity} persist={persist} />{template.blockers.length > 0 && <Panel title="Blocker"><ul className="space-y-2">{template.blockers.map((blocker) => <li key={blocker.id} className="flex gap-3 text-sm text-rose-300"><span>!</span>{blocker.label}</li>)}</ul></Panel>}{error && <p role="alert" className="text-sm text-rose-300">{error}</p>}<div className="sticky bottom-4 z-20 flex justify-end"><div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-[#0b111e]/95 p-2 shadow-2xl backdrop-blur"><span aria-live="polite" className="pl-2 text-xs text-emerald-300">{saved ? "Gespeichert" : ""}</span><button type="submit" className="min-h-11 rounded-xl bg-cyan-300 px-5 text-sm font-semibold text-slate-950 hover:bg-cyan-200">Änderungen speichern</button></div></div></div></form>; }

function OpenItems({ activity, persist }: { activity: Activity; persist: (next: Activity, kind: ChangeKind, text: string) => void }) { const [text, setText] = useState(""); const items = activity.openItems || []; function add(event: FormEvent) { event.preventDefault(); if (!text.trim()) return; const item: ActivityOpenItem = { id: crypto.randomUUID(), text: text.trim(), completed: false, createdAt: new Date().toISOString() }; persist({ ...activity, openItems: [...items, item] }, "offener-punkt", `Offener Punkt erstellt: ${item.text}`); setText(""); } function toggle(item: ActivityOpenItem) { const completed = !item.completed; persist({ ...activity, openItems: items.map((entry) => entry.id === item.id ? { ...entry, completed, completedAt: completed ? new Date().toISOString() : undefined } : entry) }, "offener-punkt", `Offener Punkt ${completed ? "erledigt" : "wieder geöffnet"}: ${item.text}`); } function remove(item: ActivityOpenItem) { persist({ ...activity, openItems: items.filter((entry) => entry.id !== item.id) }, "offener-punkt", `Offener Punkt gelöscht: ${item.text}`); } return <Panel title="Offene Punkte"><div className="space-y-2">{items.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl bg-black/15 px-3 py-3"><input type="checkbox" checked={item.completed} onChange={() => toggle(item)} className="h-5 w-5 accent-cyan-300" /><span className={`min-w-0 flex-1 text-sm ${item.completed ? "text-slate-600 line-through" : "text-slate-300"}`}>{item.text}</span><button type="button" onClick={() => remove(item)} className="px-2 py-1 text-xs text-rose-300">Löschen</button></div>)}{items.length === 0 && <p className="py-3 text-sm text-slate-600">Keine offenen Punkte vorhanden.</p>}</div><div className="mt-4 flex gap-2"><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Neuen offenen Punkt erfassen" className={inputClass} /><button type="button" onClick={add} className="shrink-0 rounded-xl bg-white/10 px-4 text-sm font-medium hover:bg-white/15">Hinzufügen</button></div></Panel>; }

function Checklist({ activity, template, persist }: { activity: Activity; template: ResolvedActivityTemplate; persist: (next: Activity, kind: ChangeKind, text: string) => void }) { const stored = activity.checklist || []; const states = new Map(stored.map((item) => [item.id, item.checked])); const templateIds = new Set(template.checklist.map((item) => item.id)); const checklist = [...template.checklist.map((item) => ({ id: item.id, label: item.label, checked: states.get(item.id) || false, blocker: item.blocker })), ...stored.filter((item) => !templateIds.has(item.id)).map((item) => ({ ...item, blocker: false }))]; function toggle(id: string) { const next = checklist.map((item) => item.id === id ? { ...item, checked: !item.checked } : item); const changed = next.find((item) => item.id === id)!; persist({ ...activity, checklist: next.map(({ id: itemId, label, checked }) => ({ id: itemId, label, checked })) }, "checkliste", `${changed.label}: ${changed.checked ? "erledigt" : "offen"}`); } return <><Title eyebrow="Template-basierte Vorbereitung" title="Checkliste" text={`${template.progress.complete} von ${template.progress.total} Template-Punkten erledigt · ${template.progress.percent} %`} /><div className="mb-6 h-2 overflow-hidden rounded-full bg-white/[0.07]"><div className="h-full rounded-full bg-cyan-300 transition-all" style={{ width: `${template.progress.percent}%` }} /></div>{checklist.length ? <div className="overflow-hidden rounded-2xl bg-white/[0.035] p-2">{checklist.map((item) => <label key={item.id} className="flex cursor-pointer items-center gap-4 rounded-xl px-4 py-4 text-sm text-slate-300 hover:bg-white/[0.035]"><input type="checkbox" checked={item.checked} onChange={() => toggle(item.id)} className="h-5 w-5 accent-cyan-300" /><span className={item.checked ? "text-slate-600 line-through" : ""}>{item.label}{item.blocker && <span className="ml-2 text-[10px] uppercase text-rose-300">Blocker</span>}{!templateIds.has(item.id) && <span className="ml-2 text-[10px] uppercase text-slate-500">Bestehender Punkt</span>}</span></label>)}</div> : <Empty>Das aufgelöste Template enthält keine Checklistenpunkte.</Empty>}</>; }

function Comments({ activity, notes, persist }: { activity: Activity; notes: ProjectNote[]; persist: (next: Activity, kind: ChangeKind, text: string) => void }) { const [text, setText] = useState(""); function add(event: FormEvent) { event.preventDefault(); if (!text.trim()) return; const comment: ActivityComment = { id: crypto.randomUUID(), text: text.trim(), author: "Bauleitung", createdAt: new Date().toISOString() }; persist({ ...activity, comments: [...(activity.comments || []), comment] }, "kommentar", "Kommentar hinzugefügt"); setText(""); } const entries = [...(activity.comments || []).map((item) => ({ ...item, category: "Kommentar" })), ...notes.map((item) => ({ id: item.id, text: item.text, author: "Bestehende Projektnotiz", createdAt: item.timestamp, category: item.category }))].sort((a,b) => b.createdAt.localeCompare(a.createdAt)); return <><Title eyebrow="Activity-Kommunikation" title="Kommentare" text="Kommentare werden direkt an dieser Activity gespeichert; bestehende Besuchsnotizen bleiben sichtbar." /><form onSubmit={add} className="mb-8 rounded-2xl bg-white/[0.035] p-5"><Area label="Neuer Kommentar" value={text} onChange={setText} placeholder="Kommentar schreiben …" /><div className="mt-3 flex items-center justify-between"><p className="text-xs text-slate-600">Autor: Bauleitung</p><button className="rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950">Kommentar speichern</button></div></form>{entries.length ? <div className="space-y-5">{entries.map((entry) => <article key={entry.id} className="border-b border-white/[0.07] pb-5"><div className="flex justify-between gap-4"><div><p className="text-sm font-medium text-slate-300">{entry.author}</p><p className="mt-1 text-[10px] uppercase tracking-[0.14em] text-cyan-300">{entry.category}</p></div><time className="text-xs text-slate-600">{formatDate(entry.createdAt)}</time></div><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-400">{entry.text}</p></article>)}</div> : <Empty>Noch keine Kommentare vorhanden.</Empty>}</>; }

function History({ activity, template }: { activity: Activity; template: ResolvedActivityTemplate }) { const entries = [...(activity.history || initialHistory(activity))].sort((a,b) => b.createdAt.localeCompare(a.createdAt)); return <><Title eyebrow="Audit Timeline" title="Verlauf" text="Änderungen bleiben chronologisch protokolliert; Folgeactivities sind ausschließlich Vorschläge." />{template.followUps.length > 0 && <Panel title="Vorgeschlagene Folgeactivities"><div className="space-y-2">{template.followUps.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl bg-black/15 px-4 py-3"><span className="text-sm text-slate-300">{item.label}</span><span className="text-[10px] uppercase text-violet-300">Vorschlag · {item.targetType}</span></div>)}</div></Panel>}<div className="relative mt-6 before:absolute before:bottom-5 before:left-[7px] before:top-5 before:w-px before:bg-white/10">{entries.map((entry) => <article key={entry.id} className="grid grid-cols-[16px_1fr] gap-5 py-5"><span className={`mt-1 h-4 w-4 rounded-full border-4 border-[#070b14] ${entry.kind === "abgeschlossen" ? "bg-emerald-400" : entry.kind === "status" ? "bg-amber-300" : "bg-cyan-300"}`} /><div className="border-b border-white/[0.07] pb-5"><p className="font-medium">{entry.text}</p><p className="mt-1 text-xs uppercase tracking-[0.12em] text-slate-600">{entry.kind}</p><time className="mt-2 block text-xs text-slate-700">{formatDate(entry.createdAt)}</time></div></article>)}</div></>; }
function Photos({ data }: { data: WorkspaceData }) { const attachments = data.activity.attachments?.filter(isImage) || []; const images = [...attachments.map((item) => ({ id: item.id, src: item.dataUrl, title: item.fileName, date: item.createdAt })), ...data.photos.map((item) => ({ id: item.id, src: item.dataUrl, title: item.description || item.fileName, date: item.timestamp }))]; return <><Title eyebrow="Dokumentation" title="Fotos" text="Vorhandene Bilder aus Activity und Baustellenbesuchen." />{images.length ? <div className="grid gap-4 sm:grid-cols-2">{images.map((item) => <figure key={item.id}><Image src={item.src} alt={item.title} width={900} height={600} unoptimized className="aspect-[4/3] w-full rounded-2xl object-cover" /><figcaption className="flex justify-between gap-4 px-1 pt-3 text-xs"><span className="text-slate-300">{item.title}</span><span className="text-slate-600">{formatDate(item.date)}</span></figcaption></figure>)}</div> : <Empty>Noch keine Fotos vorhanden.</Empty>}</>; }
function Documents({ data, template }: { data: WorkspaceData; template: ResolvedActivityTemplate }) { const attachments = data.activity.attachments?.filter((item) => !isImage(item)) || []; return <><Title eyebrow="Template-Anforderungen" title="Dokumente" text="Anforderungen stammen aus dem aufgelösten Template; vorhandene Unterlagen bleiben referenziert." />{template.documents.length > 0 && <Panel title="Dokumentanforderungen"><div className="space-y-3">{template.documents.map((item) => <div key={item.id} className="flex items-center justify-between gap-4"><span className="text-sm text-slate-300">{item.label}</span><span className={`text-xs ${item.blocker ? "text-rose-300" : "text-slate-600"}`}>{item.requirement}{item.blocker ? " · Blocker" : ""}</span></div>)}</div></Panel>}<div className="mt-5">{attachments.length || data.documents.length ? <div className="divide-y divide-white/[0.07] rounded-2xl bg-white/[0.035] px-5">{attachments.map((item) => <Doc key={item.id} title={item.fileName} meta={`${item.mediaType} · ${formatSize(item.fileSize)}`} />)}{data.documents.map((item) => <Doc key={item.id} title={item.title} meta={`${item.type} · ${item.status}`} />)}</div> : <Empty>Keine Dokumente vorhanden.</Empty>}</div></>; }

function Context({ tab, data, template }: { tab: Tab; data: WorkspaceData; template: ResolvedActivityTemplate }) { const open = (data.activity.openItems || []).filter((item) => !item.completed); const values: Array<[string,string]> = template.context.map((item) => [item.label, item.detailKey ? displayDetail(data.activity.details?.[item.detailKey]) : item.value || "Nicht hinterlegt"]); return <aside className="border-t border-white/[0.08] py-8 xl:sticky xl:top-[10.5rem] xl:border-l xl:border-t-0 xl:pl-6"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-600">Kontext · {template.label}</p><div className="mt-6 space-y-6"><section><p className="text-xs font-semibold text-slate-300">Wichtige Hinweise</p><dl className="mt-4 space-y-5">{values.map(([label,value]) => <Fact key={label} label={label} value={value} />)}</dl></section><section className="border-t border-white/[0.07] pt-5"><Fact label="Status" value={data.activity.status} /><div className="mt-5"><Fact label="Frist" value={data.activity.plannedAt ? formatDate(data.activity.plannedAt) : undefined} /></div></section><section className="border-t border-white/[0.07] pt-5"><Fact label="Offene Punkte" value={`${open.length}`} /><div className="mt-5"><Fact label="Checkliste" value={`${template.progress.complete} / ${template.progress.total}`} /></div></section>{template.blockers.length > 0 && <section className="border-t border-rose-300/10 pt-5"><p className="text-xs font-semibold text-rose-300">Blocker</p><ul className="mt-3 space-y-2">{template.blockers.map((item) => <li key={item.id} className="text-xs leading-5 text-slate-500">{item.label}</li>)}</ul></section>}{tab === "Kommentare" && <section className="border-t border-white/[0.07] pt-5"><Fact label="Kommentare" value={`${data.activity.comments?.length || 0}`} /></section>}</div></aside>; }

function DynamicField({ field, value, onChange }: { field: TemplateField; value: ActivityDetailValue | string | null | undefined; onChange: (value: ActivityDetailValue | string) => void }) { if (field.kind === "checkbox") return <label className="flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-slate-300"><input type="checkbox" checked={Boolean(value)} onChange={(event) => onChange(event.target.checked)} className="h-5 w-5 accent-cyan-300" />{field.label}</label>; if (field.kind === "textarea") return <Area label={field.label} value={typeof value === "string" ? value : ""} onChange={onChange} />; if (field.kind === "select") return <Select label={field.label} value={typeof value === "string" ? value : ""} options={field.options || []} onChange={onChange} />; const shown = field.kind === "datetime" && typeof value === "string" ? toLocalDateTime(value) : typeof value === "string" ? value : ""; return <Input label={field.label} type={field.kind === "date" ? "date" : field.kind === "datetime" ? "datetime-local" : "text"} value={shown} onChange={onChange} placeholder={field.placeholder} />; }
const inputClass = "min-h-12 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-slate-200 outline-none placeholder:text-slate-700 focus:border-cyan-300/50";
function Input({ label, value, onChange, type="text", placeholder }: { label: string; value: string; onChange: (value:string)=>void; type?: string; placeholder?: string }) { return <label><span className="mb-2 block text-sm font-medium text-slate-300">{label}</span><input type={type} value={value} onChange={(event)=>onChange(event.target.value)} placeholder={placeholder} className={inputClass}/></label>; }
function Area({ label, value, onChange, placeholder, className="" }: { label:string; value:string; onChange:(value:string)=>void; placeholder?:string; className?:string }) { return <label className={className}><span className="mb-2 block text-sm font-medium text-slate-300">{label}</span><textarea rows={4} value={value} onChange={(event)=>onChange(event.target.value)} placeholder={placeholder} className={`${inputClass} resize-y`}/></label>; }
function Select({ label, value, options, onChange }: { label:string; value:string; options:readonly string[]; onChange:(value:string)=>void }) { return <label><span className="mb-2 block text-sm font-medium text-slate-300">{label}</span><select value={value} onChange={(event)=>onChange(event.target.value)} className={inputClass}>{options.map((option)=><option key={option}>{option}</option>)}</select></label>; }
function Fact({label,value}:{label:string;value?:string}){return <div><dt className="text-[10px] uppercase tracking-[0.13em] text-slate-600">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-xs font-medium text-slate-300">{value||"Nicht hinterlegt"}</dd></div>}
function Badge({children,tone}:{children:React.ReactNode;tone:"cyan"|"green"|"rose"|"muted"}){const colors={cyan:"bg-cyan-400/10 text-cyan-300",green:"bg-emerald-400/10 text-emerald-300",rose:"bg-rose-400/10 text-rose-300",muted:"bg-white/[0.06] text-slate-400"};return <span className={`rounded-full px-3 py-1 text-[11px] font-semibold ${colors[tone]}`}>{children}</span>}
function Doc({title,meta}:{title:string;meta:string}){return <div className="flex items-center gap-4 py-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/[0.05] text-xs text-slate-500">DOC</span><div className="min-w-0"><p className="truncate text-sm font-medium">{title}</p><p className="mt-1 truncate text-xs text-slate-600">{meta}</p></div></div>}
function initialHistory(activity:Activity):ActivityHistoryEntry[]{return [{id:`created:${activity.id}`,kind:"erstellt",text:"Activity erstellt",createdAt:activity.createdAt},...(activity.status==="abgeschlossen"?[{id:`completed:${activity.id}`,kind:"abgeschlossen" as const,text:"Activity abgeschlossen",createdAt:activity.endedAt||activity.updatedAt}]:[])]}
function historyEntry(kind:ChangeKind,text:string,createdAt=new Date().toISOString()):ActivityHistoryEntry{return{id:crypto.randomUUID(),kind,text,createdAt}}
function isImage(item:ActivityAttachment){return item.mediaType.startsWith("image/")}
function displayDetail(value:ActivityDetailValue|undefined){if(typeof value==="boolean")return value?"Ja":"Nein";if(typeof value==="string")return value||"Nicht hinterlegt";if(Array.isArray(value))return `${value.length} Einträge`;return"Nicht hinterlegt"}
function templateFieldValue(activity:Activity,field:TemplateField){return field.source==="details"?activity.details?.[field.key]:(activity as unknown as Record<string,ActivityDetailValue|string|null|undefined>)[field.key]}
function activityFieldValue(field:TemplateField,value:ActivityDetailValue|string){if(field.key==="plannedAt")return typeof value==="string"&&value?new Date(value).toISOString():null;if(field.key==="responsibleId")return typeof value==="string"?value:null;return value}
function toLocalDateTime(value:string|null){if(!value)return"";const date=new Date(value);const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16)}
function formatAddress(project:Project){return[project.address,[project.postalCode,project.city].filter(Boolean).join(" ")].filter(Boolean).join(", ")}
function formatDate(value:string){return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function formatSize(bytes:number){return bytes<1024*1024?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1024/1024).toFixed(1)} MB`}
function State({text}:{text:string}){return <AppShell><div className="flex min-h-screen items-center justify-center px-6 text-sm text-slate-500">{text}</div></AppShell>}
