"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import type { Activity } from "@/types/activity";
import type { ProjectDocument } from "@/types/document";
import type { MaterialEntry } from "@/types/material";
import type { ProjectNote } from "@/types/note";
import type { ProjectPhoto } from "@/types/photo";
import type { Project } from "@/types/project";
import type { ProjectCockpitData } from "@/types/project-cockpit";
import type { MeasurementEntry } from "@/types/project-core";
import type { SiteVisit } from "@/types/site-visit";

export const projectTabs = ["Übersicht", "Aktivitäten", "Dokumente", "Fotos", "Rechnungen", "Termine", "Material", "Kolonne", "KI", "Verlauf"] as const;
export type ProjectTab = (typeof projectTabs)[number];

export type ProjectWorkspaceData = { project: Project; activities: Activity[]; photos: ProjectPhoto[]; documents: ProjectDocument[]; notes: ProjectNote[]; measurements: MeasurementEntry[]; materialEntries: MaterialEntry[]; visits: SiteVisit[]; cockpit: ProjectCockpitData; preparationPercent: number };

export function ProjectWorkspace({ tab, data, onOpenActivity, onPrepareOffer, onConfirmOffer, onSaveCockpit, onChangeOpenWork, onChangeOpenQuestions, saved }: { tab: ProjectTab; data: ProjectWorkspaceData; onOpenActivity: () => void; onPrepareOffer: () => void; onConfirmOffer: () => void; onSaveCockpit: () => void; onChangeOpenWork: (value: string) => void; onChangeOpenQuestions: (value: string) => void; saved: boolean }) {
  return <div className="grid items-start gap-8 xl:grid-cols-[minmax(0,1fr)_248px]">
    <main className="min-w-0 py-8">
      {tab === "Übersicht" && <Overview data={data} onOpenActivity={onOpenActivity} onSaveCockpit={onSaveCockpit} onChangeOpenWork={onChangeOpenWork} onChangeOpenQuestions={onChangeOpenQuestions} saved={saved} />}
      {tab === "Aktivitäten" && <Activities data={data} onOpenActivity={onOpenActivity} />}
      {tab === "Dokumente" && <Documents data={data} onPrepareOffer={onPrepareOffer} onConfirmOffer={onConfirmOffer} />}
      {tab === "Fotos" && <Photos data={data} />}
      {tab === "Rechnungen" && <Invoices data={data} />}
      {tab === "Termine" && <Dates data={data} />}
      {tab === "Material" && <Material data={data} />}
      {tab === "Kolonne" && <Crew data={data} />}
      {tab === "KI" && <Assistant data={data} />}
      {tab === "Verlauf" && <History data={data} />}
    </main>
    <ContextRail tab={tab} data={data} />
  </div>;
}

function WorkspaceTitle({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: React.ReactNode }) { return <header className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-cyan-300">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight text-white sm:text-3xl">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{text}</p></div>{action}</header>; }
function Panel({ title, eyebrow, children, className = "" }: { title: string; eyebrow?: string; children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl bg-white/[0.035] p-5 sm:p-6 ${className}`}><div>{eyebrow && <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-600">{eyebrow}</p>}<h3 className="mt-1 text-base font-semibold text-slate-100">{title}</h3></div><div className="mt-5">{children}</div></section>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="flex min-h-32 items-center justify-center rounded-xl border border-dashed border-white/10 px-6 text-center text-sm leading-6 text-slate-600">{children}</div>; }
function Metric({ label, value, tone = "plain" }: { label: string; value?: string; tone?: "plain" | "cyan" | "amber" }) { return <div><dt className="text-[11px] uppercase tracking-[0.12em] text-slate-600">{label}</dt><dd className={`mt-2 text-sm font-medium ${tone === "cyan" ? "text-cyan-300" : tone === "amber" ? "text-amber-300" : "text-slate-200"}`}>{value || "Nicht hinterlegt"}</dd></div>; }

function Overview({ data, onOpenActivity, onSaveCockpit, onChangeOpenWork, onChangeOpenQuestions, saved }: { data: ProjectWorkspaceData; onOpenActivity: () => void; onSaveCockpit: () => void; onChangeOpenWork: (value: string) => void; onChangeOpenQuestions: (value: string) => void; saved: boolean }) {
  const { project, activities, materialEntries, cockpit, preparationPercent } = data;
  const open = activities.filter(isOpen); const today = activities.filter((item) => item.plannedAt?.slice(0, 10) === dateKey(new Date())); const changes = activities.filter((item) => item.type === "Nachtrag" && isOpen(item));
  return <><WorkspaceTitle eyebrow="Operativer Überblick" title="Was dieses Projekt jetzt braucht" text="Sechs klare Arbeitsfelder – verdichtet aus der bestehenden Projektakte." action={<button onClick={onOpenActivity} className="rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-cyan-200">Neue Aktivität</button>} />
    <div className="grid gap-4 lg:grid-cols-2">
      <Panel title="Projektstatus" eyebrow="Status"><div className="grid grid-cols-2 gap-6"><Metric label="Lebenszyklus" value={project.phase || project.status} tone="cyan" /><Metric label="Vorbereitung" value={`${preparationPercent} %`} /><Metric label="Offene Activities" value={`${open.length}`} /><Metric label="Nächster Einsatz" value={day(cockpit.nextDeployment.plannedDate)} /></div></Panel>
      <Panel title="Heute" eyebrow="Priorität">{today.length ? <CompactActivities items={today.slice(0, 4)} /> : <Empty>Für heute sind keine Activities geplant.</Empty>}</Panel>
      <Panel title="Offene Punkte" eyebrow="Operativ"><div className="space-y-4"><TextArea label="Offene Arbeiten" value={cockpit.operational.openWork} onChange={onChangeOpenWork} placeholder="Keine offenen Arbeiten erfasst." /><TextArea label="Offene Fragen" value={cockpit.operational.openQuestions} onChange={onChangeOpenQuestions} placeholder="Keine offenen Fragen erfasst." /><div className="flex items-center justify-end gap-3"><span className="text-xs text-emerald-300">{saved ? "Gespeichert" : ""}</span><button onClick={onSaveCockpit} className="rounded-lg bg-white/10 px-4 py-2 text-xs font-semibold text-slate-200 hover:bg-white/15">Speichern</button></div></div></Panel>
      <Panel title="Fortschritt" eyebrow="Projekt"><Progress phase={project.phase} /></Panel>
      <Panel title="Material" eyebrow="Versorgung"><div className="grid grid-cols-2 gap-6"><Metric label="Einträge" value={`${materialEntries.length}`} /><Metric label="Geplanter Bedarf" value={project.estimatedMaterial} /><Metric label="Einsatzplanung" value={cockpit.nextDeployment.plannedWork} /><Metric label="Aufmaßstatus" value={cockpit.technical.measurementStatus} /></div></Panel>
      <Panel title="Rechnungen" eyebrow="Kaufmännisch"><div className="grid grid-cols-2 gap-6"><Metric label="Angebot" value={cockpit.commercial.offerStatus || project.offer?.status} /><Metric label="Abschlag" value={cockpit.commercial.progressInvoiceStatus} /><Metric label="Offene Nachträge" value={cockpit.commercial.openChanges || `${changes.length}`} tone={changes.length ? "amber" : "plain"} /><Metric label="Schlussrechnung" value={cockpit.commercial.finalInvoiceStatus} /></div></Panel>
    </div></>;
}

function Activities({ data, onOpenActivity }: { data: ProjectWorkspaceData; onOpenActivity: () => void }) {
  const [filter, setFilter] = useState("Alle"); const filters = ["Alle", "Offen", "Heute", "Kritisch", "Erledigt", "Telefonat", "Montage", "Material", "Nachtrag"];
  const items = [...data.activities].filter((item) => filter === "Alle" || filter === "Offen" && isOpen(item) || filter === "Heute" && item.plannedAt?.slice(0, 10) === dateKey(new Date()) || filter === "Kritisch" && item.priority === "kritisch" || filter === "Erledigt" && !isOpen(item) || filter === "Material" && item.type.startsWith("Material") || item.type === filter).sort((a,b) => (b.plannedAt || b.updatedAt).localeCompare(a.plannedAt || a.updatedAt));
  return <><WorkspaceTitle eyebrow="Activity Engine" title="Aktivitäten" text="Operativer Verlauf, nicht eine zweite Aufgabenlogik." action={<button onClick={onOpenActivity} className="rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950">Neue Aktivität</button>} /><div className="mb-7 flex gap-2 overflow-x-auto pb-2">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-medium ${filter === item ? "bg-white text-slate-950" : "bg-white/[0.05] text-slate-400 hover:text-white"}`}>{item}</button>)}</div>{items.length ? <div className="relative space-y-0 before:absolute before:bottom-6 before:left-[7px] before:top-6 before:w-px before:bg-white/10">{items.map((item) => { const content = <><span className={`mt-1 h-4 w-4 rounded-full border-4 border-[#070b14] ${item.priority === "kritisch" ? "bg-rose-400" : isOpen(item) ? "bg-cyan-300" : "bg-emerald-400"}`} /><div className="border-b border-white/[0.07] pb-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-600">{item.type}</p><h3 className="mt-1 font-semibold text-slate-100">{item.title}</h3></div><span className="text-xs text-slate-500">{item.plannedAt ? formatDate(item.plannedAt) : formatDate(item.updatedAt)}</span></div>{item.description && <p className="mt-2 text-sm leading-6 text-slate-400">{item.description}</p>}<div className="mt-3 flex gap-3 text-xs text-slate-600"><span>{item.status}</span><span>·</span><span>{item.priority}</span></div></div></>; const className="relative grid grid-cols-[16px_minmax(0,1fr)] gap-5 py-5 transition hover:bg-white/[0.015]"; return item.id.startsWith("site-visit:") ? <Link key={item.id} href={`/projects/${data.project.id}/visits/${item.id.slice("site-visit:".length)}`} className={className}>{content}</Link> : <Link key={item.id} href={`/projects/${data.project.id}/activities/${item.id}`} className={className}>{content}</Link> })}</div> : <Empty>Für diesen Filter sind keine Activities vorhanden.</Empty>}</>;
}

function Documents({ data, onPrepareOffer, onConfirmOffer }: { data: ProjectWorkspaceData; onPrepareOffer: () => void; onConfirmOffer: () => void }) { const groups = ["Angebot", "Sicherheit", "Montage", "Aufmaß", "Nachträge", "Weitere Unterlagen"]; const docs = data.documents; return <><WorkspaceTitle eyebrow="Projektakte" title="Dokumente" text="Unterlagen nach fachlichem Zweck geordnet, statt als flache Dateiliste." />{data.project.offer ? <div className="mb-5 flex items-center justify-between rounded-2xl bg-cyan-400/[0.07] p-5"><div><p className="text-xs text-cyan-300">Angebot {data.project.offer.number}</p><p className="mt-1 font-semibold">{data.project.offer.status}</p></div>{data.project.offer.status !== "angenommen" && <button onClick={onConfirmOffer} className="rounded-lg bg-cyan-300 px-4 py-2 text-xs font-semibold text-slate-950">Auftrag bestätigen</button>}</div> : <button onClick={onPrepareOffer} className="mb-5 rounded-xl bg-white/10 px-4 py-2.5 text-sm font-medium">Angebot vorbereiten</button>}<div className="grid gap-px overflow-hidden rounded-2xl bg-white/[0.07] sm:grid-cols-2">{groups.map((group) => { const matches = docs.filter((doc) => documentGroup(doc) === group); return <section key={group} className="min-h-44 bg-[#0b101b] p-6"><div className="flex items-center justify-between"><h3 className="font-semibold">{group}</h3><span className="text-xs text-slate-600">{matches.length}</span></div>{matches.length ? <div className="mt-5 space-y-4">{matches.map((doc) => <div key={doc.id}><p className="text-sm text-slate-300">{doc.title}</p><p className="mt-1 text-xs text-slate-600">{doc.status} · {formatDate(doc.updatedAt)}</p></div>)}</div> : <p className="mt-8 text-sm text-slate-600">Keine Unterlage vorhanden.</p>}</section>})}</div></> }

function Photos({ data }: { data: ProjectWorkspaceData }) { const activityPhotos = data.activities.flatMap((activity) => (activity.attachments || []).filter((file) => file.mediaType.startsWith("image/")).map((file) => ({ id: file.id, src: file.dataUrl, title: file.fileName, date: file.createdAt, source: activity.title }))); const seen = new Set<string>(); const images = [...data.photos.map((photo) => ({ id: photo.id, src: photo.dataUrl, title: photo.description || photo.fileName, date: photo.timestamp, source: `Baustellenbesuch ${photo.visitId}` })), ...activityPhotos].filter((image) => { const key = `${image.src.slice(0,120)}:${image.title}`; if (seen.has(key)) return false; seen.add(key); return true; }).sort((a,b) => b.date.localeCompare(a.date)); return <><WorkspaceTitle eyebrow="Projektdokumentation" title="Fotos" text="Große Vorschauen aus Baustellenbesuchen, Projektfotos und Activity-Anhängen." />{images.length ? <div className="grid gap-4 sm:grid-cols-2">{images.map((item, index) => <figure key={item.id} className={index % 5 === 0 ? "sm:col-span-2" : ""}><Image src={item.src} alt={item.title} width={1000} height={650} unoptimized className={`w-full rounded-2xl object-cover ${index % 5 === 0 ? "aspect-[16/8]" : "aspect-[4/3]"}`} /><figcaption className="flex justify-between gap-4 px-1 pt-3 text-xs"><span className="text-slate-300">{item.title}</span><span className="text-right text-slate-600">{item.source}<br />{formatDate(item.date)}</span></figcaption></figure>)}</div> : <Empty>Noch keine Bilder in dieser Projektakte.</Empty>}</> }

function Invoices({ data }: { data: ProjectWorkspaceData }) { const c = data.cockpit.commercial; const changes = data.activities.filter((a) => a.type === "Nachtrag"); return <><WorkspaceTitle eyebrow="Kaufmännisch" title="Rechnungen" text="Statusbild aus Angebots-, Miet- und Rechnungsdaten des Project Cockpits." /><div className="grid gap-4 sm:grid-cols-3"><Panel title="Abschlagsrechnungen" className="sm:col-span-2"><div className="grid gap-6 sm:grid-cols-3"><Metric label="Status" value={c.progressInvoiceStatus} tone="cyan" /><Metric label="Letzter Abschlag" value={day(c.lastProgressInvoiceDate)} /><Metric label="Offene Forderungen" /></div></Panel><Panel title="Nachträge"><p className="text-4xl font-semibold">{changes.length}</p><p className="mt-2 text-sm text-slate-500">Vorgänge in Activities</p></Panel><Panel title="Schlussrechnung"><Metric label="Status" value={c.finalInvoiceStatus} /></Panel><Panel title="Mietzeit"><div className="space-y-5"><Metric label="Mietbeginn" value={day(c.rentalStart)} /><Metric label="Abmeldung" value={day(c.deregistrationDate)} /></div></Panel><Panel title="Mietmengen"><Metric label="Abrechenbar" value={c.billableRentalQuantities} /></Panel></div></> }

function Dates({ data }: { data: ProjectWorkspaceData }) { const events = [...data.activities.filter(a => a.plannedAt).map(a => ({ id:a.id, date:a.plannedAt!, title:a.title, type:a.type, href:undefined as string|undefined })), ...data.visits.map(v => ({ id:v.id, date:v.date, title:v.type, type:"Baustellenbesuch", href:`/projects/${data.project.id}/visits/${v.id}` }))].sort((a,b)=>a.date.localeCompare(b.date)); return <><WorkspaceTitle eyebrow="Projektzeit" title="Termine" text="Eine Zeitachse aus bestehenden Activities und Baustellenbesuchen." />{events.length ? <div>{events.map((event) => { const content=<div className="grid grid-cols-[96px_1fr] gap-6 border-b border-white/[0.07] py-5"><p className="text-sm font-semibold text-cyan-300">{formatDay(event.date)}</p><div><p className="font-medium">{event.title}</p><p className="mt-1 text-xs text-slate-600">{event.type}</p></div></div>; return event.href ? <Link key={`${event.type}:${event.id}`} href={event.href} className="block hover:bg-white/[0.02]">{content}</Link> : <div key={`${event.type}:${event.id}`}>{content}</div>})}</div> : <Empty>Keine projektbezogenen Termine vorhanden.</Empty>}</> }

function Material({ data }: { data: ProjectWorkspaceData }) { const acts=data.activities.filter(a=>a.type.startsWith("Material")); return <><WorkspaceTitle eyebrow="Versorgung" title="Material" text="Materialstatus aus vorhandenen Einträgen und Material-Activities." /><div className="grid gap-6 lg:grid-cols-[1fr_0.8fr]"><Panel title="Materialbestand im Projekt">{data.materialEntries.length ? <div className="divide-y divide-white/[0.07]">{data.materialEntries.map(e=><div key={e.id} className="grid grid-cols-[1fr_auto] gap-4 py-4 first:pt-0"><div><p className="text-sm font-medium">{e.name}</p><p className="mt-1 text-xs text-slate-600">{e.source} · {formatDate(e.timestamp)}</p></div><p className="font-semibold text-cyan-300">{e.quantity} {e.unit}</p></div>)}</div>:<Empty>Keine Materialeinträge vorhanden.</Empty>}</Panel><Panel title="Materialvorgänge">{acts.length?<CompactActivities items={acts}/>:<Empty>Keine Material-Activities vorhanden.</Empty>}</Panel></div></> }
function Crew({ data }: { data: ProjectWorkspaceData }) { return <><WorkspaceTitle eyebrow="Einsatzteam" title="Kolonne" text="Projektbezogene Ressourcensicht ohne zusätzliche Dispositionslogik." /><div className="rounded-2xl bg-white/[0.035] p-6 sm:p-8"><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3"><Metric label="Kolonne" /><Metric label="Vorarbeiter" /><Metric label="Mitarbeiter" /><Metric label="Fahrzeuge" /><Metric label="Geräte" /><Metric label="Einsatzzeitraum" value={day(data.cockpit.nextDeployment.plannedDate)} /></div><div className="mt-8 border-t border-white/[0.07] pt-6"><p className="text-sm text-slate-500">Für dieses Projekt sind noch keine eigenen Personal- oder Ressourcendaten hinterlegt.</p></div></div></> }
function Assistant({ data }: { data: ProjectWorkspaceData }) { return <><WorkspaceTitle eyebrow="Projektassistent" title="Projektkontext verstehen" text="Der Assistent wird auf diese Projektakte begrenzt – ohne Chat-Oberfläche und noch ohne generierte Antworten." /><div className="overflow-hidden rounded-3xl bg-gradient-to-br from-violet-400/[0.10] via-white/[0.035] to-cyan-400/[0.06] p-7 sm:p-10"><div className="max-w-2xl"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-300 text-sm font-bold text-slate-950">AI</div><h3 className="mt-8 text-2xl font-semibold">Bereit für den Projektkontext</h3><p className="mt-3 leading-7 text-slate-400">Später kann der Assistent vorhandene Activities, Dokumente, Termine, Nachträge und Projektdaten für {data.project.name} auswerten. In diesem Grundzustand werden keine Antworten erzeugt.</p><div className="mt-8 flex flex-wrap gap-2">{["Fehlende Unterlagen", "Offene Arbeiten", "Letztes Telefonat", "Offene Nachträge", "Nächster Termin"].map(x=><span key={x} className="rounded-full bg-black/20 px-3 py-2 text-xs text-slate-400">{x}</span>)}</div></div></div></> }
function History({ data }: { data: ProjectWorkspaceData }) { const events=[...data.activities.map(a=>({id:a.id,date:a.updatedAt,title:a.title,detail:`${a.type} · ${a.status}`,href:a.id.startsWith("site-visit:")?`/projects/${data.project.id}/visits/${a.id.slice(11)}`:undefined})),...data.notes.map(n=>({id:n.id,date:n.timestamp,title:n.category,detail:n.text,href:undefined})),{id:`project:${data.project.id}`,date:data.project.createdAt,title:"Projekt angelegt",detail:data.project.status,href:undefined}].sort((a,b)=>b.date.localeCompare(a.date)); return <><WorkspaceTitle eyebrow="Audit Timeline" title="Verlauf" text="Chronologie aus bestehenden Activities, Notizen und Projektinformationen." /><div className="relative before:absolute before:bottom-5 before:left-[7px] before:top-5 before:w-px before:bg-white/10">{events.map(e=>{const content=<div className="relative grid grid-cols-[16px_1fr] gap-5 py-5"><span className="mt-1 h-4 w-4 rounded-full border-4 border-[#070b14] bg-slate-500"/><div className="border-b border-white/[0.07] pb-5"><p className="font-medium">{e.title}</p><p className="mt-1 text-sm text-slate-500">{e.detail}</p><p className="mt-2 text-xs text-slate-700">{formatDate(e.date)}</p></div></div>;return e.href?<Link key={e.id} href={e.href}>{content}</Link>:<div key={e.id}>{content}</div>})}</div></> }

function ContextRail({ tab, data }: { tab: ProjectTab; data: ProjectWorkspaceData }) { const open=data.activities.filter(isOpen); const critical=open.filter(a=>a.priority==="kritisch"); const calls=open.filter(a=>a.type==="Telefonat"); const next=[...data.activities].filter(a=>a.plannedAt&&isOpen(a)).sort((a,b)=>a.plannedAt!.localeCompare(b.plannedAt!)).slice(0,3); let focus: Array<[string,string]> = [["Projektstatus", data.project.phase||data.project.status],["Offene Punkte",`${open.length}`]]; if(tab==="Aktivitäten") focus=[["Kritisch",`${critical.length}`],["Rückrufe",`${calls.length}`]]; if(tab==="Dokumente") focus=[["Unterlagen",`${data.documents.length}`],["Angebot",data.project.offer?.status||"Nicht vorhanden"]]; if(tab==="Fotos") focus=[["Bilder",`${data.photos.length}`],["Neueste Aufnahme",data.photos[0]?formatDay(data.photos[0].timestamp):"Keine"]]; if(tab==="Rechnungen") focus=[["Abschlag",data.cockpit.commercial.progressInvoiceStatus||"Offen"],["Nachträge",`${data.activities.filter(a=>a.type==="Nachtrag").length}`]]; if(tab==="Material") focus=[["Materialpositionen",`${data.materialEntries.length}`],["Bedarf",data.project.estimatedMaterial||"Nicht hinterlegt"]]; return <aside className="border-t border-white/[0.08] py-8 xl:sticky xl:top-[9.25rem] xl:border-t-0 xl:border-l xl:pl-6"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-600">Kontext · {tab}</p><div className="mt-6 space-y-6"><section><p className="text-xs font-semibold text-slate-300">Im Fokus</p><dl className="mt-3 space-y-4">{focus.map(([l,v])=><Metric key={l} label={l} value={v}/>)}</dl></section><section className="border-t border-white/[0.07] pt-5"><p className="text-xs font-semibold text-slate-300">Nächste Termine</p>{next.length?<div className="mt-3 space-y-4">{next.map(a=><div key={a.id}><p className="text-xs text-cyan-300">{formatDay(a.plannedAt!)}</p><p className="mt-1 text-sm text-slate-400">{a.title}</p></div>)}</div>:<p className="mt-3 text-xs leading-5 text-slate-600">Keine offenen Termine.</p>}</section>{critical.length>0&&<section className="border-t border-rose-300/10 pt-5"><p className="text-xs font-semibold text-rose-300">Projektwarnungen</p><p className="mt-2 text-sm text-slate-400">{critical.length} kritische {critical.length===1?"Activity":"Activities"}</p></section>}<section className="border-t border-white/[0.07] pt-5"><p className="text-xs font-semibold text-slate-300">KI-Hinweis</p><p className="mt-2 text-xs leading-5 text-slate-600">Projektassistent ist vorbereitet, aber noch nicht aktiv.</p></section></div></aside> }

function CompactActivities({ items }: { items: Activity[] }) { return <div className="divide-y divide-white/[0.07]">{items.map(a=><div key={a.id} className="flex items-start justify-between gap-4 py-3 first:pt-0 last:pb-0"><div><p className="text-sm font-medium text-slate-200">{a.title}</p><p className="mt-1 text-xs text-slate-600">{a.type} · {a.status}</p></div>{a.priority==="kritisch"&&<span className="text-xs text-rose-300">kritisch</span>}</div>)}</div> }
function TextArea({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string}){return <label><span className="mb-2 block text-xs text-slate-500">{label}</span><textarea rows={3} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full resize-y rounded-xl border border-white/[0.08] bg-black/20 px-3 py-2.5 text-sm text-slate-200 outline-none placeholder:text-slate-700 focus:border-cyan-300/40"/></label>}
function Progress({phase}:{phase?:Project["phase"]}){const steps=["Angebot","Vorbereitung","Projekt","Abrechnung","Archiv"];const current=phase==="archiviert"?4:phase==="abgeschlossen"||phase==="Abrechnung"?3:phase==="Anfrage"||phase==="Angebot"?0:phase==="Auftrag bestätigt"||phase==="Vorbereitung"?1:2;return <ol className="space-y-4">{steps.map((s,i)=><li key={s} className="flex items-center gap-3"><span className={`h-2.5 w-2.5 rounded-full ${i<current?"bg-emerald-400":i===current?"bg-cyan-300 ring-4 ring-cyan-300/10":"bg-white/10"}`}/><span className={`text-sm ${i===current?"font-semibold text-white":"text-slate-500"}`}>{s}{i===current&&phase?` · ${phase}`:""}</span></li>)}</ol>}
function documentGroup(doc:ProjectDocument){if(doc.type==="Montageanweisung")return"Montage";if(doc.type==="Gefährdungsbeurteilung")return"Sicherheit";if(doc.type==="Aufmaß")return"Aufmaß";if(doc.type==="Nachtrag")return"Nachträge";return"Weitere Unterlagen"}
function isOpen(a:Activity){return !["abgeschlossen","storniert"].includes(a.status)}
function dateKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function day(v:string){return v?formatDay(v):""}
function formatDate(v:string){return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}
function formatDay(v:string){return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium"}).format(new Date(v.includes("T")?v:`${v}T12:00:00`))}
